version: '3.3'
services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'Enme'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${USUARIO_BANCO}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${SENHA_BANCO}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${SENHA_BANCO_ROOT}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '${PORT_BANCO}:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: